name = "skilo-api"
main = "src/index.ts"
compatibility_date = "2024-12-31"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "skilo"
database_id = "109e2039-e037-4ad5-b194-8ff5c7db7176"

[[r2_buckets]]
binding = "SKILLPACK_BUCKET"
bucket_name = "skilo-bundles"

[[kv_namespaces]]
binding = "SKILLPACK_KV"
id = "ee9048598adc4d24a46a4432781f71b0"

[env.production]
d1_databases = [
  { binding = "DB", database_name = "skilo-prod", database_id = "<your-prod-database-id>" }
]

[build]
command = ""